name: Arm Runner Space

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Vorher
        run: |
          echo "--- Vorher"
          df -h

      - name: Maximize build space
        uses: Zabrimus/maximize-build-space@master

      - name: Nachher
        run: |
          echo "--- Nachher"
          df -h

