name: Arm Runner

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build All
        run: |
          df -h
          dpkg -l
          
          sudo docker image prune --all --force
          sudo apt-get remove -y --purge '^docker-ce.*'
          
          sudo apt-get remove -y --purge apache2 \
              clang-16 clang-17 clang-18 \
              clang-format-16 clang-format-17 clang-format-18 \
              clang-tidy-16 clang-tidy-17 clang-tidy-18 \
              cpp-12 cpp-13 \
              docker-ce 
          
          sudo apt update
          sudo apt -y install gcc make git unzip wget xz-utils bc gperf zip g++ xfonts-utils xsltproc openjdk-11-jre-headless libxml-parser-perl lzop libjson-parse-perl libjson-perl \
              libparse-yapp-perl libncurses5-dev bc bzip2 diffutils gawk gcc gperf gzip file patchutils lzop make patch perl sed tar unzip wget xz-utils zip zstd \
              libncurses5-dev libc6-dev libparse-yapp-perl libxml-parser-perl qemu-user-binfmt g++ xfonts-utils xsltproc rdfind

          sudo snap remove $(snap list | awk '!/^Name|^core|^snapd/ {print $1}') || true
          sudo apt -y --purge purge snapd || true

          df -h
          dpkg -l