name: Arm Runner

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build All
        run: |
          df -h
          uname -a
          gcc -v
          
