name: Build CoreELEC-19

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build All"]
    type:
      - complete

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build CoreELEC-19
        run: |
          echo "Build CoreELEC-19..."
