name: Build LibreELEC-master-arm

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build LibreELEC-master-arm
        run: |
          echo "Build LibreELEC-master-arm..."
