name: Build Subworkflow

on:
  workflow_call:
    inputs:
      runner:
        description: "Runner"
        default: ubuntu-20.04
        required: true
        type: string

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-22.04
    outputs:
      runner: ${{ steps.runner.outputs.runner }}
    steps:
      - name: Choose runner
        id: runner
        run: |
          echo "runner=${{ inputs.runner }}" >> $GITHUB_OUTPUT

  build:
    needs: [ setup ]
    runs-on: ${{ needs.setup.outputs.runner }}
    name: Name
    steps:
      - name: Print System
        run: |
          uname -a
          
