name: Build LibreELEC-master-arm-Allwinner-H6

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build All"]
    type:
      - complete

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build LibreELEC-master-arm-Allwinner-H6
        run: |
          echo "Build LibreELEC-master-arm-Allwinner-H6..."

