name: Build Failure

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build All"]
    type:
      - complete

jobs:
  pre_build:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v4
        with:
          concurrent_skipping: 'always'

  build:
    needs: pre_build
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Failure
        run: |
          echo "Build Failure..."
          exit 1
