name: cc-test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    name: build
    steps:
      - name: Maximize build space
        uses: Zabrimus/maximize-build-space@master

      - name: Install packages
        shell: bash
        run: |
          sudo apt update
          sudo apt-get install -y \
             bash bc bzip2 cpio cpp-12 curl diffutils elfutils file g++-12 gawk gcc-12 git golang-1.23-go gperf gzip \
             libc6-dev libelf-dev libglib2.0-0 libglib2.0-dev libjson-perl libncurses5-dev \
             libparse-yapp-perl libxml-parser-perl lzop make openjdk-11-jdk openssh-client patch patchutils perl \
             python3 python3-build python3-installer python3-setuptools python3-wheel python-is-python3 \
             rdfind rsync sed libjson-parse-perl tar unzip upx-ucl wget \
             xfonts-utils xsltproc xz-utils zip zstd \
             --no-install-recommends

          if [ "$(uname -m)" = "aarch64" ]; then
            sudo apt-get install -y libc6-amd64-cross qemu-user-binfmt --no-install-recommends;
          fi

          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100 \
            --slave /usr/bin/cpp cpp /usr/bin/cpp-12 \
            --slave /usr/bin/g++ g++ /usr/bin/g++-12 \
            --slave /usr/bin/gcov gcov /usr/bin/gcov-12
          sudo update-alternatives --config gcc              

          sudo snap remove $(snap list | awk '!/^Name|^core|^snapd/ {print $1}') || true
          sudo apt -y --purge purge snapd openjdk-21-jre-headless || true
          sudo apt -y --purge autoremove
          sudo apt clean

          (cd / && sudo ln -s /usr/x86_64-linux-gnu/lib64 lib64)

          gcc --version
          g++ --version          
      
          ls -la /usr/bin
          
