name: Glob Test

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      target:
        description: "build"
        type: choice
        options:
          - CoreELEC-20
          - CoreELEC-21
          - CoreELEC-22
          - LibreELEC-12
          - LibreELEC-13
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Create folder and files
        run: |
          mkdir -p LibreELEC.tv/target
          mkdir -p CoreELEC/target
          
          touch LibreELEC.tv/target/LibreELEC-A6.aarch64-12.2-VDR-1014.kernel
          touch LibreELEC.tv/target/LibreELEC-A6.aarch64-12.2-VDR-1014.system
          touch LibreELEC.tv/target/LibreELEC-A6.aarch64-12.2-VDR-1014.tar
          touch LibreELEC.tv/target/LibreELEC-A6.aarch64-12.2-VDR-1014.tar.sha256
          
          touch LibreELEC.tv/target/LibreELEC-AMLGX.aarch64-12.2-VDR-1014-alta.img.gz
          touch LibreELEC.tv/target/LibreELEC-AMLGX.aarch64-12.2-VDR-1014-alta.img.gz.sha256
          touch LibreELEC.tv/target/LibreELEC-AMLGX.aarch64-12.2-VDR-1014-bananapi-m2-pro.img.gz
          touch LibreELEC.tv/target/LibreELEC-AMLGX.aarch64-12.2-VDR-1014-bananapi-m2-pro.img.gz.sha256

          touch LibreELEC.tv/target/LibreELEC-AMLGX.aarch64-12.2-VDR-1014-xlta.img.gz
          touch LibreELEC.tv/target/LibreELEC-AMLGX.aarch64-12.2-VDR-1014-ylta.img.gz.sha256
          touch LibreELEC.tv/target/LibreELEC-AMLGX.aarch64-12.2-VDR-1014-znanapi-m2-pro.img.gz
          touch LibreELEC.tv/target/LibreELEC-AMLGX.aarch64-12.2-VDR-1014-Qananapi-m2-pro.img.gz.sha256

          touch LibreELEC.tv/target/LibreELEC-Generic-legacy.x86_64-12.2-VDR-1013.img.gz
          touch LibreELEC.tv/target/LibreELEC-Generic-legacy.x86_64-12.2-VDR-1013.img.gz.sha256
          touch LibreELEC.tv/target/LibreELEC-Generic-legacy.x86_64-12.2-VDR-1013.ova
          touch LibreELEC.tv/target/LibreELEC-Generic-legacy.x86_64-12.2-VDR-1013.ova.sha256
          touch LibreELEC.tv/target/LibreELEC-Generic-legacy.x86_64-12.2-VDR-1013.tar
          touch LibreELEC.tv/target/LibreELEC-Generic-legacy.x86_64-12.2-VDR-1013.tar.sha256
          
          touch CoreELEC/target/CE-Amlogic-ne.aarch64-20.5-VDR-1013-Generic.img.gz
          touch CoreELEC/target/CE-Amlogic-ne.aarch64-20.5-VDR-1013-Generic.img.gz.sha256
          touch CoreELEC/target/CE-Amlogic-ne.aarch64-20.5-VDR-1013-Khadas_VIM1S.img.gz
          touch CoreELEC/target/CE-Amlogic-ne.aarch64-20.5-VDR-1013-Zhadas_VIM1S.img.gz.sha256
          touch CoreELEC/target/CE-Amlogic-ne.aarch64-20.5-VDR-1013-Zadas_VIM4.img.gz
          touch CoreELEC/target/CE-Amlogic-ne.aarch64-20.5-VDR-1013-Xhadas_VIM4.img.gz.sha256
          touch CoreELEC/target/CE-Amlogic-ne.aarch64-20.5-VDR-1013.tar
          touch CoreELEC/target/CE-Amlogic-ne.aarch64-20.5-VDR-1013.tar.sha256
          touch CoreELEC/target/CE-Amlogic-ne.aarch64-21.2-VDR-1013-Generic.img.gz
          touch CoreELEC/target/CE-Amlogic-ne.aarch64-21.2-VDR-1013-Generic.img.gz.sh

      - name: Rename
        run: |
          ( cd LibreELEC.tv/target
          
            for i in `ls *.{tar,img.gz,sha256,ova}`; do
              if [ -f $i ]; then
                NEWNAME=$(echo $i | perl -pe "s/^LibreELEC/LE/");
                NEWNAME=$(echo $NEWNAME | perl -pe "s/^CoreELEC/CE/");
                mv $i $NEWNAME || true
              fi
            done;
          )

          ( cd CoreELEC/target
          
            for i in `ls *.{tar,img.gz,sha256,ova}`; do
              if [ -f $i ]; then
                NEWNAME=$(echo $i | perl -pe "s/^CoreELEC/CE/");
                NEWNAME=$(echo $NEWNAME | perl -pe "s/^CoreELEC/CE/");
                mv $i $NEWNAME || true
              fi
            done;
          )
          
          ls -la LibreELEC.tv/target
          ls -la CoreELEC/target

      - name: Save release target files (part 1)
        uses: actions/upload-artifact@v4
        with:
          name: "build-artifacts-2025-10-17.1-CoreELEC-20-ng-3"
          compression-level: 0
          retention-days: 1
          overwrite: true
          if-no-files-found: ignore
          path: |
              CoreELEC/target/CE*-VDR-????-[a-kA-K]*
              LibreELEC.tv/target/LE*-VDR-????-[a-kA-K]*

      - name: Save release target files (part 2)
        uses: actions/upload-artifact@v4
        with:
          name: "build-artifacts-2025-10-17.1-CoreELEC-21-ne-3"
          compression-level: 0
          retention-days: 1
          overwrite: true
          if-no-files-found: ignore
          path: |
            CoreELEC/target/CE*-VDR-????-[l-zL-Z]*
            LibreELEC.tv/target/LE*-VDR-????-[l-zL-Z]*

      - name: Save release target files (part 3)
        uses: actions/upload-artifact@v4
        with:
          name: "build-artifacts-2025-10-17.1-CoreELEC-22-no-3"
          compression-level: 0
          retention-days: 1
          overwrite: true
          if-no-files-found: ignore
          path: |
            CoreELEC/target/CE*-VDR-????.*
            LibreELEC.tv/target/LE*-VDR-????.*

      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          path: build-artifacts
          pattern: build-artifacts-*${{ inputs.target }}*
          merge-multiple: true

      - name: List files
        run: |
          ls -la build-artifacts