name: Maximize V4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Preinstall packages
        run: |
          sudo apt update
          sudo apt install eatmydata aptitude
          sudo ln -s /usr/lib/x86_64-linux-gnu/libeatmydata.so /usr/lib/libeatmydata.so

      - name: Remove all packages which are not in important or required
        run: |
          # remove at first snap
          sudo systemctl mask snapd || true
          sudo snap remove $(snap list | awk '!/^Name|^core|^snapd/ {print $1}') || true
          sudo apt -y --purge purge snapd || true
          
          apt --dry-run  purge $(aptitude search '~i!~M!~prequired!~pimportant!~R~prequired!~R~R~prequired!~R~pimportant!~R~R~pimportant!initramfs-tools!eatmydata' | awk '{print $2}')

          # sudo eatmydata apt -y --purge purge $(dpkg-query -Wf '${Package;-40}${Priority}\n' | sort -b -k2,2 -k1,1 | grep -v -E "required|important" | awk '{ print $1 }' | xargs) || true

      - name: Show disk usage
        run: df -h

      #- name: Top-level directories
      #  run: sudo du -h -d1 / | sort -hr | head -n 20

      #- name: Detailed file sizes
      #  run: sudo find / -type f -exec du -h {} + 2>/dev/null | sort -hr | head -n 1000
