name: Maximize V4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Preinstall packages
        run: |
          sudo apt update
          sudo apt install eatmydata aptitude
          sudo ln -s /usr/lib/x86_64-linux-gnu/libeatmydata.so /usr/lib/libeatmydata.so

      - name: Remove all packages which are not in important or required
        run: |
          # remove at first snap
          sudo systemctl disable snapd || true
          sudo snap remove $(snap list | awk '!/^Name|^core|^snapd/ {print $1}') || true
          sudo eatmydata apt -y --purge purge snapd || true          
          sudo eatmydata apt -y purge $(aptitude search '~i!~M!~prequired!~pimportant!~R~prequired!~R~R~prequired!~R~pimportant!~R~R~pimportant!initramfs-tools!eatmydata!shim-signed' | awk '{print $2}')
          sudo eatmydata apt -y autoremove

      - name: Show disk usage
        run: df -h

      #- name: Top-level directories
      #  run: sudo du -h -d1 / | sort -hr | head -n 20

      #- name: Detailed file sizes
      #  run: sudo find / -type f -exec du -h {} + 2>/dev/null | sort -hr | head -n 1000
