name: Maximize V4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show disk usage
        run: df -h

      - name: Top-level directories
        run: du -h -d1 / | sort -hr | head -n 20

      - name: Detailed file sizes
        run: find / -type f -exec du -h {} + 2>/dev/null | sort -hr | head -n 1000

      - name: List all packages of Ubuntu minimal
        run: |
          echo <<EOF >packages-minimal
          adduser
          apt
          apt-utils
          base-files
          base-passwd
          bash
          bsdutils
          ca-certificates
          console-setup
          console-setup-linux
          coreutils
          cron
          dash
          dbus
          debconf
          debconf-i18n
          debianutils
          diffutils
          distro-info
          distro-info-data
          dmsetup
          dpkg
          e2fsprogs
          eject
          findutils
          fuse3
          gcc-12-base:amd64
          gir1.2-glib-2.0:amd64
          gpgv
          grep
          gzip
          hostname
          init
          init-system-helpers
          iproute2
          iputils-ping
          isc-dhcp-client
          isc-dhcp-common
          iso-codes
          kbd
          keyboard-configuration
          kmod
          language-pack-en
          language-pack-en-base
          less
          libacl1:amd64
          libapparmor1:amd64
          libapt-pkg6.0:amd64
          libargon2-1:amd64
          libatm1:amd64
          libattr1:amd64
          libaudit-common
          libaudit1:amd64
          libblkid1:amd64
          libbpf0:amd64
          libbsd0:amd64
          libbz2-1.0:amd64
          libc-bin
          libc6:amd64
          libcap-ng0:amd64
          libcap2:amd64
          libcap2-bin
          libcbor0.8:amd64
          libcom-err2:amd64
          libcrypt1:amd64
          libcryptsetup12:amd64
          libdb5.3:amd64
          libdbus-1-3:amd64
          libdebconfclient0:amd64
          libdevmapper1.02.1:amd64
          libdns-export1110
          libedit2:amd64
          libelf1:amd64
          libestr0:amd64
          libexpat1:amd64
          libext2fs2:amd64
          libfastjson4:amd64
          libffi8:amd64
          libfido2-1:amd64
          libfribidi0:amd64
          libfuse3-3:amd64
          libgcc-s1:amd64
          libgcrypt20:amd64
          libgirepository-1.0-1:amd64
          libglib2.0-0:amd64
          libglib2.0-data
          libgmp10:amd64
          libgnutls30:amd64
          libgpg-error0:amd64
          libgpm2:amd64
          libgssapi-krb5-2:amd64
          libhogweed6:amd64
          libicu70:amd64
          libidn2-0:amd64
          libip4tc2:amd64
          libisc-export1105:amd64
          libjson-c5:amd64
          libk5crypto3:amd64
          libkeyutils1:amd64
          libkmod2:amd64
          libkrb5-3:amd64
          libkrb5support0:amd64
          liblocale-gettext-perl
          liblz4-1:amd64
          liblzma5:amd64
          libmd0:amd64
          libmnl0:amd64
          libmount1:amd64
          libmpdec3:amd64
          libncurses6:amd64
          libncursesw6:amd64
          libnetplan0:amd64
          libnettle8:amd64
          libnewt0.52:amd64
          libnsl2:amd64
          libnss-systemd:amd64
          libp11-kit0:amd64
          libpam-cap:amd64
          libpam-modules:amd64
          libpam-modules-bin
          libpam-runtime
          libpam-systemd:amd64
          libpam0g:amd64
          libpcre2-8-0:amd64
          libpcre3:amd64
          libpopt0:amd64
          libprocps8:amd64
          libpython3-stdlib:amd64
          libpython3.10:amd64
          libpython3.10-minimal:amd64
          libpython3.10-stdlib:amd64
          libreadline8:amd64
          libseccomp2:amd64
          libselinux1:amd64
          libsemanage-common
          libsemanage2:amd64
          libsepol2:amd64
          libslang2:amd64
          libsmartcols1:amd64
          libsodium23:amd64
          libsqlite3-0:amd64
          libss2:amd64
          libssl3:amd64
          libstdc++6:amd64
          libsystemd0:amd64
          libtasn1-6:amd64
          libtext-charwidth-perl
          libtext-iconv-perl
          libtext-wrapi18n-perl
          libtinfo6:amd64
          libtirpc-common
          libtirpc3:amd64
          libudev1:amd64
          libunistring2:amd64
          libuuid1:amd64
          libx11-6:amd64
          libx11-data
          libxau6:amd64
          libxcb1:amd64
          libxdmcp6:amd64
          libxext6:amd64
          libxml2:amd64
          libxmuu1:amd64
          libxtables12:amd64
          libxxhash0:amd64
          libyaml-0-2:amd64
          libzstd1:amd64
          locales
          login
          logrotate
          logsave
          lsb-base
          lsb-release
          mawk
          media-types
          mount
          ncurses-base
          ncurses-bin
          netbase
          netcat-openbsd
          netplan.io
          networkd-dispatcher
          openssh-client
          openssl
          passwd
          perl-base
          procps
          python-apt-common
          python3
          python3-apt
          python3-dbus
          python3-gi
          python3-minimal
          python3-netifaces:amd64
          python3-pkg-resources
          python3-yaml
          python3.10
          python3.10-minimal
          readline-common
          rsyslog
          sed
          sensible-utils
          shared-mime-info
          sudo
          systemd
          systemd-hwe-hwdb
          systemd-sysv
          systemd-timesyncd
          sysvinit-utils
          tar
          tzdata
          ubuntu-advantage-tools
          ubuntu-keyring
          ubuntu-minimal
          ubuntu-pro-client
          ubuntu-pro-client-l10n
          ucf
          udev
          usrmerge
          util-linux
          vim
          vim-common
          vim-runtime
          vim-tiny
          whiptail
          xauth
          xdg-user-dirs
          xkb-data
          xxd
          zlib1g:amd64
          EOF

      - name: Remove all packages which are not in Ubuntu minimal
        run: |
          for i in $(dpkg -l | awk '{ print $2 }'); do
             if [ $(grep -ic $i packages-minimal) -eq 0 ]; then 
                echo "Delete package $i"
             fi
          done  
