name: Build All2

on:
  workflow_dispatch:
    inputs:
      gitref_to_build:
        description: "gitref tag or hash to build"
        default: vdrelec-20-VDR
        required: true
        type: string
      target:
        description: "targets to build"
        default: all
        required: true
        type: choice
        options:
          - all
          - H6.arm
          - H3.arm
          - H5.arm
          - A64.arm
          - R40.arm
          - Amlogic-ng.arm

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build All
        run: |
          echo "Build All..."
          
          echo "-------------------------------"
          echo "Create Release notes..."
          echo "-------------------------------"
          
          VREV=$(git ls-remote https://github.com/${{ github.repository }} | head -1 | sed "s/HEAD//" | cut -c 1-7)
          
          echo ">>> Step 1"
          
          echo "VDRSternELEC: [master@${VREV}](https://github.com/${{ github.repository }}/tree/${VREV})" >> release_notes
          
          echo ">>> Step 2"
          
          echo "" >> release_notes
          
          echo ">>> Step 3"
          
          echo "----------------------------------------------------------------------------" >> release_notes
          
          echo ">>> Step 4"
          
          echo "| Status  | Distro | Project | Device | Revision |" >> release_notes
          
          echo ">>> Step 5"
          
          echo "| ------- | ------ | ------- | ------ | -------- |" >> release_notes
          
          echo ">>> Step 6"
          
          cat build-summary/build-summary* >> release_notes || true
          
          echo ">>> Step 7"
          
          cat release_notes
          
          echo ">>> Step 8"
