name: Build All2

on:
  workflow_dispatch:
    inputs:
      gitref_to_build:
        description: "gitref tag or hash to build"
        default: vdrelec-20-VDR
        required: true
        type: string
      target:
        description: "targets to build"
        default: all
        required: true
        type: choice
        options:
          - all
          - H6.arm
          - H3.arm
          - H5.arm
          - A64.arm
          - R40.arm
          - Amlogic-ng.arm

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build All
        run: |
          echo "Build All..."
          
          VREV=$(git ls-remote https://github.com/${{ github.repository }} | head -1 | sed "s/HEAD//" | cut -c 1-7)
          echo "VREF = ${VREV}
